<?php
/**
 * Created by PhpStorm.
 * User: topone4tvs
 * Date: 2018/3/28
 * Time: 10:50
 */
namespace Omnipay\Jyalipay;

use Omnipay\Alipay\AopAppGateway;
use Omnipay\Common\Message\AbstractRequest;
use Omnipay\Jyalipay\Requests\AgpCompletePayAndSignRequest;
use Omnipay\Jyalipay\Requests\AgpPayAndSignAgreementRequest;
use Omnipay\Jyalipay\Requests\AgpUnSignAgreementRequest;

class AgreementGateway extends AopAppGateway
{
    /**
     * Get gateway display name
     *
     * This can be used by carts to get the display name for each gateway.
     */
    public function getName()
    {
        return 'Jiuyan Alipay APP Gateway';
    }

    /**
     * @param array $parameters
     *
     * @return AgpCompletePayAndSignRequest|AbstractRequest
     */
    public function purchaseAndSignAgreement(array $parameters = [])
    {
        return $this->createRequest(AgpPayAndSignAgreementRequest::class, $parameters);
    }

    /**
     * 流程是可以互通的
     */
    public function completePurchase(array $parameters = [])
    {
        return parent::completePurchase($parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $parameters
     * @return AbstractRequest
     */
    public function unSignAgreement($parameters = [])
    {
        return $this->createRequest(AgpUnSignAgreementRequest::class, $parameters);
    }
}